### ISSUE TITLE
Cannot download software

### ISSUE THREAD

**Issue by j75** [tommy-leung/FireAnt#9]
Hello,

I've tried to follow the indications from https://github.com/jungle-elec/FireAnt/wiki/Efinity-Software-Installation-Guide, but at https://www.efinixinc.com/support/pwreset.php (using the E-mail I have used at Crowd Supply) the only thing I've got is `Unable to verify username xxxxx@gmail.com`.

Event more than that, I tried to ask for help sending an e-mail at fireant@xips.technology, but Gmail replied with
```
Address not found
--
Your message wasn't delivered to fireant@xips.technology because the address couldn't be found, or is unable to receive mail.
```
So, what should be done?

**Comment by WayneBooth** [comment]
Thanks for closing this issue without comment.
I also have the same problem. Received the board, but no SN, so cannot download software. No reply form any support address.
Please reply, otherwise I'll have to return board.

**Comment by tommy-leung** [comment]
Hi Wayne,



We are terribly sorry for missing your message.

May I know how many pcs of FireAnt did you bought?

We will prepare the SN and invitation email for you accordingly.



Best regards,

FireAnt Support Team



Jungle Electronics








---- On Mon, 28 Sep 2020 20:49:43 +0800 Wayne Booth <notifications@github.com> wrote ----





Thanks for closing this issue without comment.
 I also have the same problem. Received the board, but no SN, so cannot download software. No reply form any support address.
 Please reply, otherwise I'll have to return board.

**Comment by tommy-leung** [comment]
Hi Wayne,

We are terribly sorry for missing your message.

May I know how many pcs of FireAnt did you bought?

We will prepare the SN and invitation email for you accordingly.





FireAnt Support Team



Jungle Electronics








---- On Mon, 28 Sep 2020 20:49:43 +0800 Wayne Booth <notifications@github.com> wrote ----




Thanks for closing this issue without comment.
 I also have the same problem. Received the board, but no SN, so cannot download software. No reply form any support address.
 Please reply, otherwise I'll have to return board.

**Comment by WayneBooth** [comment]
Thanks for getting back to me.
I ordered just one unit for now.
Thanks.
Wayne Booth

**Comment by j75** [comment]
I also ordered one; could you send me an E-mail too, please?

**Comment by tommy-leung** [comment]
Hi j75,

I can't address your email here?
Can you send an email to fireant@jungle-elec.com
Besides, how many pcs of FireAnt did you ordered?
I will send the SN and Efinix Support Center Register Invitation email for you accordingly.

Best regards,

**Comment by j75** [comment]
On Tue, 2020-09-29 at 17:30 -0700, Tommy Leung wrote:
> Hi j75,

Hi !
> I can't address your email here?

Yes, of course.

> Besides, how many pcs of FireAnt did you ordered?

only one (at least for the moment).

> I will send the SN and Efinix Support Center Register Invitation
> email for you accordingly.

Thank you very much!

Best regards,

M. Ion

**Comment by j75** [comment]
Hi! any news concerning that invitation email?

**Comment by tommy-leung** [comment]
Hi, Ion.

We've sent you the invitation email on 4th Oct and just resend again. Could you receive the email? Could you check also the junk box?

Thanks

**Comment by j75** [comment]
yes, now I've got it, thanks!
